# Generated by Django 5.1.6 on 2025-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0004_remove_product_category_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_published",
        ),
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store_app.category"
            ),
        ),
    ]
