# Generated by Django 5.2 on 2025-04-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0005_remove_product_is_published_alter_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
