# Generated by Django 5.1.6 on 2025-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_product_is_available_product_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="store_app.category"
            ),
        ),
    ]
