name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r home_works/hw_12/requirements.txt
        pip install pytest pytest-cov pytest-django
        
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: hw_12.store_app.settings
      run: |
        cd home_works/hw_12
        python manage.py migrate
        pytest store_app/tests --cov=./ --cov-report=xml
       
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3