name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      working-directory: ./home_works/hw_12
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-django
        pip list  # Для отладки - покажет установленные пакеты
        
    - name: Verify Django installation
      working-directory: ./home_works/hw_12
      run: |
        python -c "import django; print(django.__version__)"
        
    - name: Run tests
      working-directory: ./home_works/hw_12
      env:
        DJANGO_SETTINGS_MODULE: config.settings
        PYTHONPATH: ${{ github.workspace }}/home_works/hw_12
      run: |
        python manage.py migrate
        pytest store_app/tests --cov=./ --cov-report=xml
       
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3